# Generated by Django 5.2 on 2026-06-10 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent_name', models.CharField(max_length=50, verbose_name='Имя родителя')),
                ('child_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7, message='Минимальный возраст — 7 лет.'), django.core.validators.MaxValueValidator(17, message='Максимальный возраст — 17 лет.')], verbose_name='Возраст ребенка')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Введите корректный номер телефона: только цифры, опциональный '+' в начале, всего от 10 до 15 цифр.", regex='^\\+?\\d{10,15}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('note', models.TextField(blank=True, max_length=700, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text', models.TextField(max_length=500, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать на сайте')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
