# Generated by Django 5.2 on 2025-04-29 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='child_age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7, message='Минимальный возраст — 7 лет.'), django.core.validators.MaxValueValidator(17, message='Максимальный возраст — 17 лет.')], verbose_name='Возраст ребенка'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Введите корректный номер телефона: только цифры, опциональный '+' в начале, всего от 10 до 15 цифр.", regex='^\\+?\\d{10,15}$')], verbose_name='Номер телефона'),
        ),
    ]
