# Generated by Django 5.0.4 on 2025-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень подготовки')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (занятий)')),
                ('min_age', models.PositiveIntegerField(verbose_name='Минимальный возраст')),
            ],
        ),
    ]
