# Generated by Django 5.2 on 2025-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень подготовки')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (занятий)')),
                ('min_age', models.PositiveIntegerField(verbose_name='Минимальный возраст')),
                ('is_hit', models.BooleanField(default='False', verbose_name='Отображение курса на главной')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers_photos/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Специализация')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Ссылки на социальные сети')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('courses', models.ManyToManyField(related_name='teachers', to='education.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
