# Generated by Django 5.2 on 2026-06-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень подготовки')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (занятий)')),
                ('min_age', models.PositiveIntegerField(verbose_name='Минимальный возраст')),
                ('is_hit', models.BooleanField(default='False', verbose_name='Отображение курса на главной')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Имя родителя')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя ученика')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия ученика')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст ученика')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers_photos/', verbose_name='Фото')),
                ('social_links', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ссылки на социальные сети')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(related_name='teachers', to='education.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True, verbose_name='Дата записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('schedule_text', models.TextField(blank=True, max_length=500, verbose_name='Расписание')),
                ('meet_link', models.URLField(blank=True, verbose_name='Ссылка на урок')),
                ('balance_lessons', models.PositiveIntegerField(default=0, verbose_name='Количество уроков')),
                ('last_homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='education.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course')],
            },
        ),
    ]
