# Generated by Django 5.0.4 on 2025-04-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_hit',
            field=models.BooleanField(default='False', verbose_name='Отображение курса на главной'),
        ),
    ]
