# Generated by Django 5.2 on 2025-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_course_options_course_is_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers_photos/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Ссылки на социальные сети')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('courses', models.ManyToManyField(related_name='teachers', to='education.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
