# Generated by Django 5.2 on 2025-04-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='social_links',
        ),
    ]
