# Generated by Django 5.2 on 2025-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_student_age_alter_student_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='education.teacher', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст ученика'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Ссылки на социальные сети'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='Специализация'),
            preserve_default=False,
        ),
    ]
