# Generated by Django 5.2 on 2025-04-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_teacher_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
