# Generated by Django 5.2 on 2025-05-01 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_teacher_students_student_teachers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_lesson_date', models.DateTimeField(blank=True, null=True)),
                ('meet_link', models.URLField(blank=True)),
                ('balance_lessons', models.PositiveIntegerField(default=0)),
                ('last_homework', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teacher')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
