# Generated by Django 5.2 on 2025-04-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='start_date',
        ),
    ]
