# Generated by Django 5.2 on 2025-04-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_teacher_photo_remove_teacher_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='education.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ссылки на социальные сети'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
    ]
