# Generated by Django 5.2 on 2025-05-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='balance_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_homework',
            field=models.TextField(blank=True, verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='meet_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на урок'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='next_lesson_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующего урока'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teacher', verbose_name='Преподаватель'),
        ),
    ]
