# Generated by Django 5.2 on 2025-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_teacher_courses_teacher_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers_photos/', verbose_name='Фото'),
        ),
    ]
