# Generated by Django 5.2 on 2025-04-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='start_date',
        ),
    ]
