# Generated by Django 5.2 on 2025-04-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_teacher_bio_remove_teacher_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='education.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ссылки на социальные сети'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
    ]
