# Generated by Django 5.2 on 2026-06-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(verbose_name='О компании')),
                ('mission_text', models.TextField(verbose_name='Наша миссия')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Whatsapp')),
                ('telegram_login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин Telegram(без @)')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Ссылка на Instagram')),
                ('vk_link', models.URLField(blank=True, verbose_name='Ссылка на VK')),
                ('youtube_link', models.URLField(blank=True, verbose_name='Ссылка на YouTube')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта (latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота (longitude)')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('rocket', 'Скорость 🚀 (rocket)'), ('lightbulb', 'Идеи и творчество 💡 (lightbulb)'), ('trophy', 'Достижения и награды 🏆 (trophy)'), ('star', 'Отличные результаты ⭐ (star)'), ('heart', 'Любовь к обучению ❤️ (heart)'), ('thumbs-up', 'Уверенность 👍 (thumbs-up)'), ('bolt', 'Энергия и мотивация ⚡ (bolt)'), ('award', 'Признание 🥇 (award)'), ('shield-alt', 'Безопасность 🛡️ (shield-alt)'), ('play', 'Игровой подход 🎮 (play)'), ('upload', 'Рост навыков ⬆️ (upload)'), ('check', 'Гарантия качества ✔️ (check)'), ('book', 'База знаний 📚 (book)'), ('code', 'Программирование 👨\u200d💻 (code)'), ('brain', 'Развитие мышления 🧠 (brain)'), ('puzzle-piece', 'Решение задач 🧩 (puzzle-piece)'), ('users', 'Дружное сообщество 👥 (users)'), ('chalkboard-teacher', 'Опытные наставники 👩\u200d🏫 (chalkboard-teacher)')], max_length=20, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(default='', max_length=100, verbose_name='Верхняя часть основного текста')),
                ('bottom_text', models.CharField(default='', max_length=100, verbose_name='Нижняя часть основного текста')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Hero-блок',
                'verbose_name_plural': 'Hero-блок',
            },
        ),
        migrations.CreateModel(
            name='ThankYouText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application', 'Заявка'), ('review', 'Отзыв')], max_length=50, unique=True, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст благодарности')),
            ],
            options={
                'verbose_name': 'Текст благодарности',
                'verbose_name_plural': 'Тексты благодарностей',
            },
        ),
    ]
