# Generated by Django 5.2 on 2025-04-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('play', 'Play'), ('upload', 'Upload'), ('check', 'Check'), ('star', 'Star'), ('heart', 'Heart'), ('thumbs-up', 'Thumbs Up'), ('bolt', 'Bolt'), ('lightbulb', 'Lightbulb'), ('rocket', 'Rocket'), ('shield-alt', 'Shield'), ('trophy', 'Trophy'), ('award', 'Award')], max_length=20)),
            ],
        ),
    ]
