# Generated by Django 5.2 on 2025-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='telegram_login',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин Telegram(без @)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Whatsapp'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефон'),
        ),
    ]
