# Generated by Django 5.2 on 2025-04-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_contactinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankyoutext',
            name='type',
            field=models.CharField(choices=[('application', 'Заявка'), ('review', 'Отзыв')], max_length=50, unique=True, verbose_name='Тип страницы'),
        ),
    ]
